{{- if and .Values.hpa.keda.enabled .Values.hpa.keda.requestsPerSecond -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ template "appname" . }}-scaledobject
spec:
  scaleTargetRef:
    name: {{ template "appname" . }}
  minReplicaCount: {{ .Values.hpa.minReplicas }}
  maxReplicaCount: {{ .Values.hpa.maxReplicas }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.hpa.keda.serverAddress }}
        metricName: {{ template "appname" . }}_req_sec
        threshold: {{ .Values.hpa.keda.requestsPerSecond | quote }}
        query: sum(rate(nginx_ingress_controller_requests{ {{ .Values.hpa.keda.filter }}='{{.Release.Namespace}}'}[2m]))
{{- end -}}
